AGENT_NUM_ITER = 2  # how many iteration before must have a answer
MEMORY_K = 5    # how many iteration kept in memory
OPEN_AI_TEMPRATURE = 0
OPENAI_API_KEY = ""
AGENT_VERBOSE = True
OPENAI_MODEL = "gpt-3.5-turbo-0125" #gpt-3.5-turbo-0125 or gpt-4-0125-preview
BACK_END_DEBUG = True
RETRIEVE_MAX_LENGTH = 5000 # max document length my char
RETRIEVE_MAX_SIZE = 10 # max number of documents retrieved
DATAPATH = "data"  #path from current directory to datasets