AGENT_NUM_ITER = 3  
MEMORY_K = 5        
OPEN_AI_TEMPRATURE = 0
OPENAI_API_KEY = "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"
AGENT_VERBOSE = True
OPENAI_MODEL = "gpt-3.5-turbo-0125"
BACK_END_DEBUG = True